/**:
  ros__parameters:
    waypoint_names: ["home", "pose1", "pose2"]
    
    home: [0.0, -0.2, 0.6, 0.0, 1.0, 0.0, 0.0] 
    pose1: [0.4, 0.2, 0.5, 0.0, 1.0, 0.0, 0.0]
    pose2: [0.4, -0.2, 0.5, 0.0, 1.0, 0.0, 0.0]
